// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdmngfxcbcndrznbmxbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkbW5nZnhjYmNuZHJ6bmJteGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTE1MjksImV4cCI6MjA1OTY4NzUyOX0.MfJUMUGX14hUbvmCTliO8ZGNT8UUlQ_-F1E-5tojw3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);